[package]
name = "lenso-wasip2-driver"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
futures.workspace = true
lenso-kernel = { path = "../lenso-kernel", version = "0.1.1" }

[dev-dependencies]
lenso-app-plan = { path = "../lenso-app-plan", version = "0.1.0" }

[lints]
workspace = true
