[package]
name = "lenso-native-adapter"
version = "0.2.2"
edition.workspace = true
license.workspace = true
publish = true
repository.workspace = true
description = "Native Rust Execution Adapter for Lenso vNext."

[package.metadata.lenso]
package-id = "lenso.native-adapter"

[dependencies]
futures.workspace = true
inventory.workspace = true
lenso-app-plan.workspace = true
lenso-kernel.workspace = true
lenso-native-adapter-macros = { version = "0.1.2", path = "../lenso-native-adapter-macros" }
serde_json.workspace = true

[dev-dependencies]
lenso-module-authoring.workspace = true
serde.workspace = true

[lints]
workspace = true
