[package]
name = "lenso-runner"
version = "0.2.1"
edition.workspace = true
license.workspace = true
publish = true
repository.workspace = true
description = "Native Tokio Runtime Driver and Runner for Lenso vNext."

[dependencies]
futures.workspace = true
lenso-app-plan.workspace = true
lenso-kernel.workspace = true
tokio = { workspace = true, features = ["sync"] }
cpu-time = "1.0"

[dev-dependencies]
lenso-native-adapter = { version = "0.3.1", path = "../lenso-native-adapter" }
lenso-runtime-conformance.workspace = true

[lints]
workspace = true
