[package]
name = "lenso-runner"
version = "0.1.3"
edition.workspace = true
license.workspace = true
publish = true
repository.workspace = true
description = "Native Tokio Runtime Driver and Runner for Lenso vNext."

[dependencies]
futures.workspace = true
lenso-app-plan = "0.1.0"
lenso-kernel = "0.1.4"
tokio = { workspace = true, features = ["sync"] }
cpu-time = "1.0"

[dev-dependencies]
lenso-runtime-conformance = "0.1.3"

[lints]
workspace = true
